"use strict";
const { v4: uuidv4 } = require("uuid");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const wilayas = [
      {
        code: "01",
        name: "Adrar",
        name_ar: "أدرار",
        latitude: 27.8742,
        longitude: -0.2939,
      },
      {
        code: "02",
        name: "Chlef",
        name_ar: "الشلف",
        latitude: 36.1654,
        longitude: 1.3346,
      },
      {
        code: "03",
        name: "Laghouat",
        name_ar: "الأغواط",
        latitude: 33.8,
        longitude: 2.865,
      },
      {
        code: "04",
        name: "Oum El Bouaghi",
        name_ar: "أم البواقي",
        latitude: 35.8756,
        longitude: 7.1136,
      },
      {
        code: "05",
        name: "Batna",
        name_ar: "باتنة",
        latitude: 35.556,
        longitude: 6.1742,
      },
      {
        code: "06",
        name: "Béjaïa",
        name_ar: "بجاية",
        latitude: 36.7509,
        longitude: 5.0567,
      },
      {
        code: "07",
        name: "Biskra",
        name_ar: "بسكرة",
        latitude: 34.848,
        longitude: 5.7286,
      },
      {
        code: "08",
        name: "Béchar",
        name_ar: "بشار",
        latitude: 31.6167,
        longitude: -2.2167,
      },
      {
        code: "09",
        name: "Blida",
        name_ar: "البليدة",
        latitude: 36.47,
        longitude: 2.8277,
      },
      {
        code: "10",
        name: "Bouira",
        name_ar: "البويرة",
        latitude: 36.3739,
        longitude: 3.9006,
      },
      {
        code: "11",
        name: "Tamanrasset",
        name_ar: "تمنراست",
        latitude: 22.785,
        longitude: 5.5228,
      },
      {
        code: "12",
        name: "Tébessa",
        name_ar: "تبسة",
        latitude: 35.4,
        longitude: 8.12,
      },
      {
        code: "13",
        name: "Tlemcen",
        name_ar: "تلمسان",
        latitude: 34.8828,
        longitude: -1.3167,
      },
      {
        code: "14",
        name: "Tiaret",
        name_ar: "تيارت",
        latitude: 35.3711,
        longitude: 1.3172,
      },
      {
        code: "15",
        name: "Tizi Ouzou",
        name_ar: "تيزي وزو",
        latitude: 36.7117,
        longitude: 4.0453,
      },
      {
        code: "16",
        name: "Alger",
        name_ar: "الجزائر",
        latitude: 36.7525,
        longitude: 3.042,
      },
      {
        code: "17",
        name: "Djelfa",
        name_ar: "الجلفة",
        latitude: 34.6704,
        longitude: 3.2503,
      },
      {
        code: "18",
        name: "Jijel",
        name_ar: "جيجل",
        latitude: 36.8211,
        longitude: 5.7667,
      },
      {
        code: "19",
        name: "Sétif",
        name_ar: "سطيف",
        latitude: 36.1898,
        longitude: 5.4108,
      },
      {
        code: "20",
        name: "Saïda",
        name_ar: "سعيدة",
        latitude: 34.8303,
        longitude: 0.1514,
      },
      {
        code: "21",
        name: "Skikda",
        name_ar: "سكيكدة",
        latitude: 36.8667,
        longitude: 6.9,
      },
      {
        code: "22",
        name: "Sidi Bel Abbès",
        name_ar: "سيدي بلعباس",
        latitude: 35.1897,
        longitude: -0.6308,
      },
      {
        code: "23",
        name: "Annaba",
        name_ar: "عنابة",
        latitude: 36.9,
        longitude: 7.7667,
      },
      {
        code: "24",
        name: "Guelma",
        name_ar: "قالمة",
        latitude: 36.4667,
        longitude: 7.4333,
      },
      {
        code: "25",
        name: "Constantine",
        name_ar: "قسنطينة",
        latitude: 36.365,
        longitude: 6.6147,
      },
      {
        code: "26",
        name: "Médéa",
        name_ar: "المدية",
        latitude: 36.2675,
        longitude: 2.75,
      },
      {
        code: "27",
        name: "Mostaganem",
        name_ar: "مستغانم",
        latitude: 35.9333,
        longitude: 0.0833,
      },
      {
        code: "28",
        name: "M'Sila",
        name_ar: "المسيلة",
        latitude: 35.7,
        longitude: 4.55,
      },
      {
        code: "29",
        name: "Mascara",
        name_ar: "معسكر",
        latitude: 35.3972,
        longitude: 0.1403,
      },
      {
        code: "30",
        name: "Ouargla",
        name_ar: "ورقلة",
        latitude: 31.95,
        longitude: 5.325,
      },
      {
        code: "31",
        name: "Oran",
        name_ar: "وهران",
        latitude: 35.6969,
        longitude: -0.6331,
      },
      {
        code: "32",
        name: "El Bayadh",
        name_ar: "البيض",
        latitude: 33.6833,
        longitude: 1.0167,
      },
      {
        code: "33",
        name: "Illizi",
        name_ar: "إليزي",
        latitude: 26.5,
        longitude: 8.4833,
      },
      {
        code: "34",
        name: "Bordj Bou Arréridj",
        name_ar: "برج بوعريريج",
        latitude: 36.0686,
        longitude: 4.7611,
      },
      {
        code: "35",
        name: "Boumerdès",
        name_ar: "بومرداس",
        latitude: 36.7525,
        longitude: 3.4728,
      },
      {
        code: "36",
        name: "El Tarf",
        name_ar: "الطارف",
        latitude: 36.7672,
        longitude: 8.3136,
      },
      {
        code: "37",
        name: "Tindouf",
        name_ar: "تندوف",
        latitude: 27.6742,
        longitude: -8.1472,
      },
      {
        code: "38",
        name: "Tissemsilt",
        name_ar: "تيسمسيلت",
        latitude: 35.6069,
        longitude: 1.8108,
      },
      {
        code: "39",
        name: "El Oued",
        name_ar: "الوادي",
        latitude: 33.3683,
        longitude: 6.8675,
      },
      {
        code: "40",
        name: "Khenchela",
        name_ar: "خنشلة",
        latitude: 35.4167,
        longitude: 7.1333,
      },
      {
        code: "41",
        name: "Souk Ahras",
        name_ar: "سوق أهراس",
        latitude: 36.2864,
        longitude: 7.9511,
      },
      {
        code: "42",
        name: "Tipaza",
        name_ar: "تيبازة",
        latitude: 36.5897,
        longitude: 2.4486,
      },
      {
        code: "43",
        name: "Mila",
        name_ar: "ميلة",
        latitude: 36.45,
        longitude: 6.2667,
      },
      {
        code: "44",
        name: "Aïn Defla",
        name_ar: "عين الدفلى",
        latitude: 36.2639,
        longitude: 1.9681,
      },
      {
        code: "45",
        name: "Naâma",
        name_ar: "النعامة",
        latitude: 33.2667,
        longitude: -0.3,
      },
      {
        code: "46",
        name: "Aïn Témouchent",
        name_ar: "عين تموشنت",
        latitude: 35.2975,
        longitude: -1.1403,
      },
      {
        code: "47",
        name: "Ghardaïa",
        name_ar: "غرداية",
        latitude: 32.49,
        longitude: 3.67,
      },
      {
        code: "48",
        name: "Relizane",
        name_ar: "غليزان",
        latitude: 35.7372,
        longitude: 0.5558,
      },
      // Nouvelles wilayas (2019)
      {
        code: "49",
        name: "El M'Ghair",
        name_ar: "المغير",
        latitude: 33.95,
        longitude: 5.9167,
      },
      {
        code: "50",
        name: "El Meniaa",
        name_ar: "المنيعة",
        latitude: 30.5833,
        longitude: 2.8833,
      },
      {
        code: "51",
        name: "Ouled Djellal",
        name_ar: "أولاد جلال",
        latitude: 34.4167,
        longitude: 5.0667,
      },
      {
        code: "52",
        name: "Bordj Baji Mokhtar",
        name_ar: "برج باجي مختار",
        latitude: 21.3333,
        longitude: 0.95,
      },
      {
        code: "53",
        name: "Béni Abbès",
        name_ar: "بني عباس",
        latitude: 30.1333,
        longitude: -2.1667,
      },
      {
        code: "54",
        name: "Timimoun",
        name_ar: "تيميمون",
        latitude: 29.2639,
        longitude: 0.2306,
      },
      {
        code: "55",
        name: "Touggourt",
        name_ar: "تقرت",
        latitude: 33.1,
        longitude: 6.0667,
      },
      {
        code: "56",
        name: "Djanet",
        name_ar: "جانت",
        latitude: 24.55,
        longitude: 9.4833,
      },
      {
        code: "57",
        name: "In Salah",
        name_ar: "عين صالح",
        latitude: 27.1967,
        longitude: 2.47,
      },
      {
        code: "58",
        name: "In Guezzam",
        name_ar: "عين قزام",
        latitude: 19.5667,
        longitude: 5.7667,
      },
    ];

    const now = new Date();
    const wilayasWithIds = wilayas.map((wilaya, index) => ({
      id: uuidv4(),
      ...wilaya,
      name_en: wilaya.name, // English name same as French
      is_active: true,
      order: index + 1,
      created_at: now,
      updated_at: now,
    }));

    await queryInterface.bulkInsert("wilayas", wilayasWithIds, {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("wilayas", null, {});
  },
};
